//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamEliza {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class doctor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal doctor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamEliza.doctor", typeof(doctor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;genericResponses&quot;:[{&quot;response&quot;:&quot;Do you feel strongly about discussing such things?&quot;,&quot;script&quot;:&quot;DOCTOR&quot;},{&quot;response&quot;:&quot;Does talking about this bother you?&quot;,&quot;script&quot;:&quot;DOCTOR&quot;},{&quot;response&quot;:&quot;I&apos;m not sure I understand you fully.&quot;,&quot;script&quot;:&quot;DOCTOR&quot;},{&quot;response&quot;:&quot;Please go on.&quot;,&quot;script&quot;:&quot;DOCTOR&quot;},{&quot;response&quot;:&quot;Tell me more about that.&quot;,&quot;script&quot;:&quot;DOCTOR&quot;},{&quot;response&quot;:&quot;That is interesting.  Please continue.&quot;,&quot;script&quot;:&quot;DOCTOR&quot;},{&quot;response&quot;:&quot;What does that suggest to you?&quot;,&quot;script&quot;:&quot;DOCTOR&quot;}],&quot;goodbyes&quot;:[{&quot;message&quot;:&quot;Go [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json {
            get {
                return ResourceManager.GetString("json", resourceCulture);
            }
        }
    }
}
